#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

# npx lint-staged

set -o nounset

 REPO_ROOT=$(git rev-parse --show-toplevel)
 echo "Git repo is at $REPO_ROOT"

 SITE_CHANGES=$(git status -s $REPO_ROOT | wc -l)
 echo "Detected $SITE_CHANGES changes"

 if [ "$SITE_CHANGES" -gt "0" ]; then
   echo "Checking to make sure package version was updated..."
# $(git diff -G '"version":' --cached origin/master package.json | wc -l)
   VERSION_CHANGED=$(git diff -G '"version":' --cached package.json | wc -l)

   if [ "$VERSION_CHANGED" -gt "0" ]; then
     echo "Version was updated!  Continuing..."
   else
     echo "Version was not updated :( Aborting commit."
     exit 1
   fi
 fi
